### ISSUE TITLE
transfer "chain" as plugins or attribute of painter?

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#107]
to properly implement a MomentumPainter using power.py, we need to be able specify transfer functions via the command line

they seem to be directly tied to the painter, i.e., a density painter should basically always do [NormalizeDC, RemoveDC, AnisotropicCIC], while a momentum painter or velocity painter only needs AnisotropicCIC. 

Thoughts on how to best implement this, @rainwoodman? We could make them plugins that could be set via the command line, or just define a set "transfer_chain" for each painter

**Comment by rainwoodman** [comment]
In the current code, transfer_chain as an argument of a painter is a bit strange, since painter does not apply the transfer chain -- it is the power spectrum code that applies the transfer chain. 

But as plugins is also a bit weird; at least we shall rework the way to define a field in the command line of power.py.

**Comment by rainwoodman** [comment]
Feels like we are running out of symbols. A 'field' is data source + painter + transfer chain.

**Comment by rainwoodman** [comment]
One possible syntax is

```--field DataSource:xxxx:xxxx Painter:XXX:xxxx Transfer:XX:XXXX```

That means the field arguments is parsed as an optional argument, even though they are required.

Alternatively,
```
[ DataSource:xxxx:xxxx painter=Painter:XXX:xxxx transfer=Transfer:XX:XXXX ] 
[ DataSource:xxxx:xxxx painter=Painter:XXX:xxxx transfer=Transfer:XX:XXXX ] 
```
a new type of argument 'Field' that parses the rest of command line?

**Comment by nickhand** [comment]
I think the first option is clearer, but things can get complicated pretty quickly. Ideally, we want to handle the situation where some components of the [data source + painter + transfer] are the same, i.e., the data source is the same, but the painters are different, as in the case of something like density - momentum correlations, so we don't have to read in the data twice (but the current framework doesn't support that easily, I don't think

We could leave the DataSource1 [DataSource2] as arguments and then have --painter and --transfer keywords

**Comment by rainwoodman** [comment]
For different painters to share the same data source we will need to be able to paint to several pm meshes. We need to modify pmesh to outsource the ownership of the real and complex buffer first; let's leave that for the future.

The argument parser in python does not pass along the context information of --painter and --transfer keywords, thus we cannot easily tell which DataSource it is decorating. That's why I was thinking we may need to parse the field triplets together.

**Comment by nickhand** [comment]
Hmm, okay I see your point. So which do you prefer?

**Comment by rainwoodman** [comment]
I preferred the braced syntax ([ ]). It looks nicer(shorter) than --field.

**Comment by nickhand** [comment]
Okay that works for me. I am thinking it would be nice from a user standpoint to have a way to specify default transfer values for certain painters, but maybe that is asking too much. For example, trying to paint velocity divergence requires a k-space kernel to be applied to compute divergence properly...

**Comment by rainwoodman** [comment]
Well. In this sense it makes more sense to have transfer function as part of the Painter arguments. But how would it interact with the grid painter?

**Comment by nickhand** [comment]
Hmm, yeah that would be problematic. Let's discuss this tomorrow if you'll
be around

**Comment by rainwoodman** [comment]
Sure!

**Comment by nickhand** [comment]
this has been closed now that we are reading `Fields` from the command-line
