### ISSUE TITLE
increased usage of astropy?

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#198]
There could be a few advantages to using more of the tools provided by astropy: 

- they include the six package for 2 to 3 compatibility, which could clean up some of our code
- they do also provide some versioning tools, etc, but they are perhaps overly complicated
- seems to be stable now and catching on in the community, which could potentially open up the code to a wider audience, i.e. "astropy-affiliated"?
- we are already using it for the cosmology class, so might as well take advantage of anything else we want
- would help with #197 

thoughts, @rainwoodman?

**Comment by rainwoodman** [comment]
I agree we shall somehow get affiliated with astropy. but ...

- 2to3: we shall depend on six if we have to. Let's not use those in astropy.
- versioning: our current policy seems to be working, and uses three lines of code; why the heavy lifting?
- cosmology: it really handy, other than we have a fixed set of internal units in nbodykit, and always need to de-unit-fy numbers from astropy. We can think about adding units to nbodykit, but I wonder if the risk is worth it..

Do you have a further list of tools in mind? 

Affiliated status: I dislike the idea of gaining publicity by voluntarily shovel their thingy down our throat. It doesn't hurt to have some originality in the astronomy software community. 

Most importantly, publicity gain from astropy is very little once we have a paper out. Having packages on PIP means the availability is already reasonably. 

I have a strong opinion against using their infrastructure tools: because the developers of older, main stream packages are usually more experienced, I think we shall follow their practices instead of those set by the young generation of physicists developers at astropy. 

#197: less code and looser coupling is the hall mark of a software design. From what it sounds like, the CLASS wrapper shall be made into a separate package, to ensure 'loose coupling' such that others can reuse the wrapper without nbodykit -- just like the way we have kdcount or pmesh.

**Comment by nickhand** [comment]
I think I agree with all of your points here -- just wanted to see what you thought. 

For 2to3, really the most important thing is unit testing anyways...Apparently the DataSet class was very broken in python 3 this whole time, without throwing any errors..

I've looked through the astropy docs a bit more...the infrastructure they set up is quite overwhelming at first. As you pint out, the goal should be to keep it as simple as possible, which we are doing a pretty good job of so far.

**Comment by nickhand** [comment]
closing this as resolved
