### ISSUE TITLE
restore coverage / more comprehensive tests

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#309]
we need to re-organize some tests from "examples" to more like unit tests

**Comment by nickhand** [comment]
@rainwoodman  - moving the discussion from #320 here. A few thoughts on possible upgrades / changes

1. re-factor the mpi4py_test Runner to be based on a distutils Command, so it can interface with setup.py test command
2. use pytest.main instead of the nose.main that numpy uses
3. handle parallel coverage properly, so that a simple `--coverage` flag will work in parallel, producing the single merged `coveragrc` file
4. in nbodykit, move tests for individual modules into their own "tests" sub-directory. This seems to be cleaner to me and better organized

Thoughts?

**Comment by nickhand** [comment]
@rainwoodman -- I am doing some re-organization and adding some tests...I'll put in a PR for you to take a look

I can put in a PR for re-organizing mpi4py_test too, if you think the above sounds reasonable.

**Comment by rainwoodman** [comment]
The most important feature we'd like to keep is to install the package before running the tests. As long as this feature is there I think I am ok with it.

- You are proposing removing dependency on numpy.Test.  I think this is not a bad idea, especially all testing frameworks are supposed to be 'compatible'. Still, I'd like to listen to the opinions of numpy developers on how much pytest they want to adopt -- I really had very poor impression on pytest. 

- I slightly prefer having a separate runtests.py driver instead of a bigger setup.py.  runtests.py can drive coverage tests directly, without using `setup.py test`. What do we gain by integrating the test-driver into setup.py?

- I also noticed recent version of numpy seem to have switched to setuptools. [1] We may want to add support to setuptools as well.
[1] https://github.com/numpy/numpy/blob/master/runtests.py#L357

- We can morph mpi4py_test into a generic test / coverage driver that supports MPI, and use it in all our packages. we only need a good name for it.

**Comment by nickhand** [comment]
Yes, this is what I was thinking -- preserve the build project feature, but with the testing not constrained by numpy's testing framework

* It would be good to get some more opinions on `pytest`. My impression was that `pytest` was pretty nice, and it was more the `pytest-pipeline` that we were using that was problematic. It does have some nice features that nose doesn't since nose is no longer maintained, i.e., I like the context manager to make sure code blocks raise Exceptions
* No reason for preferring `setup.py test` really -- I just thought that that was the standard way of doing things 
* The `setuptools`, `distutils`, etc differences have always confused me....there doesn't really seem to be a standard approach?

I am working on tests for the `io` module now. I am thinking the best approach is we should maintain tests of `lab` that serve more like "examples" and then tests for individuals modules can be in the spirit of unit tests, with more specific purposes for each testing function

**Comment by nickhand** [comment]
Closing this as the coverage on v0.2.x is up to 95%, with new comprehensive tests
