### ISSUE TITLE
No wiggle power spectrum

### ISSUE THREAD

**Issue by fbeutler** [bccp/nbodykit#411]
I am getting these warnings when using the ehpower class... the docs don't seem to explain the EisensteinHusetting for LinearPower? Where can I find that?

/Users/xflorian/anaconda/lib/python2.7/site-packages/nbodykit/cosmology/cosmology.py:298: UserWarning: Class did not read input parameter(s): Om0, flat
  self.engine = ClassEngine(pars)
/Users/xflorian/anaconda/lib/python2.7/site-packages/nbodykit/cosmology/power/linear.py:228: FutureWarning: NoWiggleEHPower is deprecated. Use LinearPower with transfer set to 'EisensteinHu'

**Comment by nickhand** [comment]
Yes, we are actively working on docs for a major cosmology update in recent versions, where we switched from an astropy backend to a CLASS backend. In general, we moved away from astropy syntax for various reasons, but tried to maintain as much backwards compatibility as possible.

There are no examples in the docs yet, but the API section is up to date:

http://nbodykit.readthedocs.io/en/latest/api/api.html#cosmology-nbodykit-cosmology

There are two different warnings here:
1. The constructor syntax for Cosmology that you are using is deprecated. See [the API](http://nbodykit.readthedocs.io/en/latest/api/nbodykit.cosmology.cosmology.html#nbodykit.cosmology.cosmology.Cosmology) docs. In particular, you should pass in Omega0_cdm and Omega0_b instead of Om0 
2. NoWiggleEHPower has been replaced by LinearPower with the transfer keyword set to 'NoWiggleEisensteinHu'. The API docs are available [here](http://nbodykit.readthedocs.io/en/latest/api/nbodykit.cosmology.power.linear.html#nbodykit.cosmology.power.linear.LinearPower)

**Comment by fbeutler** [comment]
thanks Nick

**Comment by rainwoodman** [comment]
Also remember in a notebook tab-completion on a cosmology object gives you everything that you can do with it (a lot of useful stuff there). The documentation doesn't include these functions yet.

**Comment by fbeutler** [comment]
Hi

After switching from om0 to the parameters Nick mentioned I am now getting
the following warning

/Users/xflorian/anaconda/envs/nbodykit-env/lib/python3.6/site-packages/nbodykit/cosmology/cosmology.py:298:
UserWarning: Class did not read input parameter(s): Omega0_b, Omega0_cdm,
flat
cheers
fl

**Comment by nickhand** [comment]
Sounds like this could be a bug somewhere. Can you post your nbodykit
version and the code snippet?

**Comment by fbeutler** [comment]
Hi Nick

I literally only call

cosmo = cosmology.Cosmology(Omega0_cdm=0.26, Omega0_b=0.04, h=0.7,
flat=True)

when getting this warning

>>> print(nbodykit.__version__)
0.2.6

cheers
fl

**Comment by nickhand** [comment]
Ah yes, you can fix this by upgrading to v0.2.7 (conda update -c bccp --all). 

We upgraded the constructor syntax to support both "Omega_X" and "Omega0_x", thinking the latter was a bit more clear (CLASS uses the "Omega_X" syntax for input). Also ``flat`` is no longer supported -- the default is flat (as in CLASS), and you can change the flatness by passing in Omega0_k as a keyword.
