### ISSUE TITLE
difference between N objects read and N from layout.exchange in paint

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#55]
* when running with more than one process, the all reduce for length of `position` returned by the `layout.exchange` in the paint() function is not equal to the total number of objects read
* this was also the case before the paint/read change, but we didn't notice because the old Painters returned the number of objects read, not the all reduce answer

I'll note that when running with only one process, the two numbers described above agree. Also, it seems that the power spectrum doesn't change when running with 1 process or several processes.

this seems like a problem, but maybe not? @rainwoodman, any idea what's going on?

**Comment by nickhand** [comment]
sorry, if it wasn't clear, the relevant script is the `paint` function in `power.py`

**Comment by rainwoodman** [comment]
This is a bug. Ntot should have been conserved and equal to the total number of particles before the exchange -- the exchange creats ghost particles for those near the edge of domains, thus give a slight larger number. 

There was not observable difference, because Ntot was only used to remove 'shot-noise', which we don't usually remove anyways.

I will commit a fix.
